# The entrypoint (dist/run.sh) is generated by the build on purpose: viam's
# cloud reload treats a module whose entrypoint already exists in the repo as
# "pre-built" and skips packaging entirely.
module.tar.gz: dist/run.sh run.sh first_run.sh requirements.txt meta.json $(shell find src -name '*.py')
	tar czf module.tar.gz --exclude='__pycache__' --exclude='*.pyc' dist/run.sh run.sh first_run.sh requirements.txt meta.json src

dist/run.sh: run.sh
	mkdir -p dist
	printf '#!/usr/bin/env bash\nexec "$$(dirname "$$0")/../run.sh" "$$@"\n' > dist/run.sh
	chmod +x dist/run.sh

setup:
	@echo "nothing to set up - the module is packaged as source"

test:
	python3 -m pytest tests/

clean:
	rm -rf module.tar.gz dist

.PHONY: setup test clean
